CREATE TABLE [Role](
	Id INT PRIMARY KEY NOT NULL,
	[name] VARCHAR(51) NOT NULL
)

CREATE TABLE [User](
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	RoleId INT NOT NULL,
	Username VARCHAR(51) NOT NULL,
	Email VARCHAR(51) NOT NULL,
	Gender VARCHAR(51) NOT NULL,
	[Password] VARCHAR(51) NOT NULL
)

ALTER TABLE [User]
	ADD FOREIGN KEY (RoleId) REFERENCES [Role](Id)

CREATE TABLE Header(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CustomerId INT NOT NULL,
	StaffId INT NOT NULL,
	[DATE] date NOT NULL
	[Status] VARCHAR(2) NOT NULL 
)

ALTER TABLE Header
	ADD FOREIGN KEY (CustomerId) REFERENCES [User](Id)

CREATE TABLE Meat(
	Id INT PRIMARY KEY NOT NULL,
	[name] VARCHAR(51) NOT NULL
)

CREATE TABLE Ramen(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Meatid INT NOT NULL,
	[Name] VARCHAR(51) NOT NULL,
	Broth VARCHAR(51) NOT NULL,
	Price VARCHAR(51) NOT NULL
)

ALTER TABLE Ramen
	ADD FOREIGN KEY (Meatid) REFERENCES Meat(Id)

CREATE TABLE Detail(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Headerid INT NOT NULL,
	Ramenid INT NOT NULL,
	Quantity INT NOT NULL
)

ALTER TABLE Detail
	ADD FOREIGN KEY (Headerid) REFERENCES Header(Id)

ALTER TABLE Detail
	ADD FOREIGN KEY (Ramenid) REFERENCES Ramen(Id)

INSERT INTO Role(Id,[name]) VALUES (1,'Admin'), (2,'Seller'), (3,'Buyer')
INSERT INTO Meat(Id,[name]) VALUES (1,'Chicken'), (2,'Beef'), (3,'Pork'), (4,'Eel'), (5,'Squid'), (6,'Fish')